<a href="https://colab.research.google.com/github/ShuvroWritesCode/Machine-Learning-with-Python-Cookbook-Practice/blob/notebook/Machine_Learning_with_Python_Cookbook_Chapter_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1.1 Creating a Vector
#### Problem: You need to create a vector.

In [ ]:
# load library
import numpy as np

# create a vector as a row
vector_row = np.array([1, 2, 3])

# create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

### 1.2 Creating a matrix

#### Problem: You need to create a matrix.

In [ ]:
# load library
import numpy as np

# create a matrix
matrix = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

### 1.3 Creating a Sparse Matrix
#### Problem: Given data with very few nonzero values, you want to efficiently represent it.

In [3]:
# load library
import numpy as np
from scipy import sparse

# create a matrix
matrix = np.array([[1, 0],
                   [0, 0],
                   [0, 6]])

# create a sparse matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

  (0, 0)	1
  (2, 1)	6


### 1.4 Preallocating NumPy Arrays
#### Problem: You need to preallocate arrays of a given size with some value

In [4]:
# load library
import numpy as np

# create a vector of 1x5 with all zeros in it
matrix1 = np.zeros(shape = 5)
print(matrix1)

# create a matrix of 3x3 with custom values
matrix2 = np.full(shape = (3,3), fill_value = 1)
print(matrix2)

[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


### 1.5 Selecting Elements
#### Problem: You need to select one or more elements in a vector or matrix

In [5]:
# load library
import numpy as np

# create a vector
vector = np.array([1, 2, 3, 4, 5])
print(vector)

# create a matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(matrix)

# access specific elements
print(vector[2])
print(matrix[1, 1])

# select elements upto 3rd elements
print(vector[:3])

# select elements from 3rd elements
print(vector[3:])

# select all elements of vector
print(vector[:])

# select last element of vector
print(vector[-1])

# reverse the vector
print(vector[::-1])

# select the first two rows and all columns of a matrix
print(matrix[:2, :])

# select all rows and the second column
print(matrix[:, 1:2])

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
5
[1 2 3]
[4 5]
[1 2 3 4 5]
5
[5 4 3 2 1]
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


### 1.6 Describing a Matrix
#### Probelm: You want to describe the shape, size and dimensions of a matrix

In [6]:
# load library
import numpy as np

# create a matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
# view number of rows and columns
print(matrix.shape)

# view total number of elements in the matrix
print(matrix.size)

# view dimension of the matrix
print(matrix.ndim)

(3, 4)
12
2


### 1.7 Applying Functions over Each Elements
#### Problem: You need to apply some functions to all elements of a matrix

In [7]:
# load library
import numpy as np

# Technique - 01 (broadcasting)
# create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix = matrix + 100
print(matrix)

# Technique - 02 (vectorize)
add_10 = lambda i : i + 10

# apply function add_10 to each element of matrix
vectorized_add_10 = np.vectorize(add_10)
matrix = vectorized_add_10(matrix)

print(matrix)

[[101 102 103]
 [104 105 106]
 [107 108 109]]
[[111 112 113]
 [114 115 116]
 [117 118 119]]


  ### 1.8 Finding the Maximum and Minimum Values
  #### Problem: You need to find the maximum and minimum values in an array

In [8]:
# load library
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# print maximum and minimum values within matrix
print(np.max(matrix))
print(np.min(matrix))

# print maximum values in each column within matrix
print(np.max(matrix, axis = 0))
# print maximum values in each row within matrix
print(np.max(matrix, axis = 1))
# print minimum values in each column within matrix
print(np.min(matrix, axis = 0))
# print minimum values in each row within matrix
print(np.min(matrix, axis = 1))

9
1
[7 8 9]
[3 6 9]
[1 2 3]
[1 4 7]


### 1.9 Calculating the average, mean and standard deviation
#### You want to calculate some descriptive statistics about an array.

In [9]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(np.mean(matrix))
print(np.var(matrix))
print(np.std(matrix))

5.0
6.666666666666667
2.581988897471611


### 1.10 eshaping Arrays
#### Problem: You need to change the shape of an array without changing the element value.

In [13]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

print(matrix.size)

new_matrix = matrix.reshape(2, 6)

print(new_matrix.size)

new_matrix2 = matrix.reshape(1, -1)

print(new_matrix2)

new_matrix3 = matrix.reshape(12)

print(new_matrix3)

12
12
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### 1.11 Transposing a Vector or Matrix
#### Problem: You need to transpose a vector or matrix

In [16]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]).T

print(matrix)

vector = np.array([1, 2, 3, 4, 5, 6]).T
print(vector)

row_matrix = np.array([[1, 2, 3, 4, 5, 6]]).T
print(row_matrix)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### 1.12 Flattening a Matrix
#### Problem: You need to transform a matrix into a one-dimensional array.

In [19]:
# load library
import numpy as np
# create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# flatten matrix
print(matrix.flatten())
# alternative to flatten()
print(matrix.reshape(1, -1))


# ravel method
# create a matrix
matrix2 = np.array([[1, 2],
                    [3, 4]])
# create another matrix
matrix3 = np.array([[5, 6],
                    [7, 8]])
# create a list of matrices
matrix_list = [matrix2, matrix3]
# flatten the entire list of matrices
np.ravel(matrix_list)

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8])

### 1.13 Finding the Rank of a Matrix
#### Problem: You need to know the rank of a matrix

In [25]:
import numpy as np
import sympy
sympy.Matrix([[1, 1, 1],[1, 1, 10],[1, 1, 15]]).rref()

print(sympy.Matrix([[1, 1, 1],[1, 1, 10],[1, 1, 15]]).rank())

2
